import type { Metadata } from "next";
import { Lato, Open_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { Toaster } from "sonner";

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-openSans-header",
  weight: ["300", "400", "500", "700", "800"],
  preload: true,
});
const lato = Lato({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lato-body",
  weight: ["100", "300", "400", "700", "900"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} ${lato.variable} antialiased`}>
        <Navbar />
        {children}
        <Footer />
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
