import type { Metadata } from "next";
import { Lato, Open_Sans } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import { Toaster } from "sonner";
import dynamic from "next/dynamic";

const Footer = dynamic(() => import("@/components/Footer"), { ssr: false });

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-openSans-header",
  weight: ["300", "400", "500", "700", "800"],
  preload: false,
  fallback: ["Arial", "sans-serif"], // Added fallback fonts
  adjustFontFallback: true, // Enables automatic font fallback adjustment
});
const lato = Lato({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lato-body",
  weight: ["100", "300", "400", "700", "900"],
  preload: false,
  fallback: ["Helvetica", "Arial", "sans-serif"], // Added fallback fonts
  adjustFontFallback: true, // Enables automatic font fallback adjustment
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} ${lato.variable} antialiased`}>
        <Navbar />
        {children}
        <Footer />
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
