local_backend: true
backend:
  name: git-gateway
  repo: jbrace817/drip-2-paint # Replace with your repo
  branch: main # Or your default branch

media_folder: "public/uploads" # Where images are stored
public_folder: "/uploads"

collections:
  # Interior Pages
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Badge", name: "badge", widget: "string" }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Gallery"
        name: "gallery"
        widget: "list"
        fields:
          - label: "Upload Image"
            name: "image_upload"
            widget: "image"
            required: false

  # Blog Posts (Linked to Authors Collection)
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - label: "Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        value_field: "name"
        search_fields: ["name"]
        display_fields: ["name"]
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Summary"
        name: "summary"
        widget: "string"
        required: false
        pattern: ["^.{0,200}$", "Summaries should be under 200 characters."]
        hint: "Auto-generated from the first 200 characters of the post."
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - "Projects"
          - "Inspiration"
          - "Tips & Techniques"
          - "Insights"
          - "Company"
          - "Community"

  # Authors Collection (Dynamically Manageable)
  - name: "authors"
    label: "Authors"
    folder: "content/authors"
    create: true
    format: "frontmatter"
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Bio", name: "bio", widget: "text", required: false }
      - {
          label: "Profile Picture",
          name: "image",
          widget: "image",
          required: false,
        }
      - label: "Social Links"
        name: "social"
        widget: "list"
        fields:
          - { label: "Platform", name: "platform", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }

  # Widgets Collection (For Banners and Modals)
  - name: "widgets"
    label: "Widgets"
    files:
      - name: "banner"
        label: "Banner Widget"
        file: "content/widgets/banner.json"
        fields:
          - { label: "Text", name: "text", widget: "string" }
          - {
              label: "Active",
              name: "active",
              widget: "boolean",
              default: false,
            }
      - name: "modal"
        label: "Modal Widget"
        file: "content/widgets/modal.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "content", widget: "text" }
          - {
              label: "Active",
              name: "active",
              widget: "boolean",
              default: false,
            }
      - name: "cta"
        label: "Call-to-Action Widgets"
        file: "content/widgets/cta.json"
        fields:
          - label: "CTAs"
            name: "ctas"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Slug (Page Path)", name: "slug", widget: "string" }
              - {
                  label: "Active",
                  name: "active",
                  widget: "boolean",
                  default: true,
                }
              - label: "Benefits"
                name: "benefits"
                widget: "list"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - {
                      label: "Description",
                      name: "description",
                      widget: "text",
                    }
